In [ ]:
!wget https://gdc.cancer.gov/files/public/file/gdc-client_v1.6.1_Ubuntu_x64.zip
!unzip gdc-client_v1.6.1_Ubuntu_x64.zip
!chmod +x gdc-client

--2026-03-04 09:22:16--  https://gdc.cancer.gov/files/public/file/gdc-client_v1.6.1_Ubuntu_x64.zip
Resolving gdc.cancer.gov (gdc.cancer.gov)... 34.206.8.134, 44.207.24.129
Connecting to gdc.cancer.gov (gdc.cancer.gov)|34.206.8.134|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://gdc.cancer.gov:443/system/files/public/file/gdc-client_v1.6.1_Ubuntu_x64.zip [following]
--2026-03-04 09:22:16--  https://gdc.cancer.gov/system/files/public/file/gdc-client_v1.6.1_Ubuntu_x64.zip
Reusing existing connection to gdc.cancer.gov:443.
HTTP request sent, awaiting response... 200 OK
Length: 23940006 (23M) [application/zip]
Saving to: ‘gdc-client_v1.6.1_Ubuntu_x64.zip’

gdc-client_v1.6.1_U 100%[===================>]  22.83M  72.9MB/s    in 0.3s

2026-03-04 09:22:17 (72.9 MB/s) - ‘gdc-client_v1.6.1_Ubuntu_x64.zip’ saved [23940006/23940006]

Archive:  gdc-client_v1.6.1_Ubuntu_x64.zip
 extracting: gdc-client

In [ ]:
!./gdc-client download -m /content/drive/MyDrive/gdc_manifest.2026-03-04.100235.txt

100% [########################################################################]
100% [#############################################] Time:  0:00:00  19.4 KiB/s
100% [#############################################] Time:  0:00:00  19.7 KiB/s
100% [#############################################] Time:  0:00:00 322.3 KiB/s
100% [#############################################] Time:  0:00:00  26.5 KiB/s
100% [#############################################] Time:  0:00:00  19.5 KiB/s
100% [#############################################] Time:  0:00:00  23.5 KiB/s
100% [#############################################] Time:  0:00:00  25.4 KiB/s
100% [#############################################] Time:  0:00:00  23.4 KiB/s
100% [#############################################] Time:  0:00:00  14.5 KiB/s
100% [#############################################] Time:  0:00:00  20.7 KiB/s
100% [#############################################] Time:  0:00:01  29.3 KiB/s
100% [#############################################] Time:  0:00:01  19.0 KiB/s
100% [#############################################] Time:  0:00:00   1.8 KiB/s
100% [#############################################] Time:  0:00:00  26.7 KiB/s
100% [#############################################] Time:  0:00:00  41.2 KiB/s
100% [#############################################] Time:  0:00:00  23.4 KiB/s
100% [#############################################] Time:  0:00:00  47.7 KiB/s
100% [#############################################] Time:  0:00:00  31.8 KiB/s
100% [#############################################] Time:  0:00:00  21.8 KiB/s
100% [#############################################] Time:  0:00:00  36.4 KiB/s
100% [#############################################] Time:  0:00:00  19.1 KiB/s
100% [#############################################] Time:  0:00:00  17.5 KiB/s
100% [#############################################] Time:  0:00:00  16.0 KiB/s
100% [#############################################] Time:  0:00:00  18.2 KiB/s
100% [#############################################] Time:  0:00:00  15.4 KiB/s
100% [#############################################] Time:  0:00:00  23.4 KiB/s
100% [#############################################] Time:  0:00:00  13.4 KiB/s
100% [#############################################] Time:  0:00:00  32.6 KiB/s
100% [#############################################] Time:  0:00:00  58.2 KiB/s
100% [#############################################] Time:  0:00:00  17.8 KiB/s
100% [#############################################] Time:  0:00:00  31.8 KiB/s
100% [#############################################] Time:  0:00:00  12.2 KiB/s
100% [#############################################] Time:  0:00:00  23.8 KiB/s
100% [#############################################] Time:  0:00:00  12.9 KiB/s
100% [#############################################] Time:  0:00:00  43.7 KiB/s
100% [#############################################] Time:  0:00:00  30.5 KiB/s
100% [#############################################] Time:  0:00:00  24.6 KiB/s
100% [#############################################] Time:  0:00:00  19.0 KiB/s
100% [#############################################] Time:  0:00:00  26.1 KiB/s
100% [#############################################] Time:  0:00:00  18.9 KiB/s
100% [#############################################] Time:  0:00:00  27.2 KiB/s
100% [#############################################] Time:  0:00:00  54.5 KiB/s
100% [#############################################] Time:  0:00:00  26.1 KiB/s
100% [#############################################] Time:  0:00:00  26.2 KiB/s
100% [#############################################] Time:  0:00:00  26.4 KiB/s
100% [#############################################] Time:  0:00:00  23.3 KiB/s
100% [#############################################] Time:  0:00:00  18.2 KiB/s
100% [#############################################] Time:  0:00:00   4.1 MiB/s
100% [#############################################] Time:  0:00:00  53.8 KiB/s
100% [#############################################] Time:  0:00:00  32.1 KiB/s
100% [#############################################] Time:  0:00:00  23.5 KiB/s
100% [#############################################] Time:  0:00:00  32.9 KiB/s
100% [#############################################] Time:  0:00:00   9.9 KiB/s
100% [#############################################] Time:  0:00:00  20.8 KiB/s
100% [#############################################] Time:  0:00:00  16.1 KiB/s
100% [#############################################] Time:  0:00:01  16.9 KiB/s
100% [#############################################] Time:  0:00:00  19.5 KiB/s
100% [#############################################] Time:  0:00:00  26.3 KiB/s
100% [#############################################] Time:  0:00:00  35.8 KiB/s
100% [#############################################] Time:  0:00:00  35.7 KiB/s
100% [#############################################] Time:  0:00:00  44.5 KiB/s
100% [#############################################] Time:  0:00:00  25.8 KiB/s
100% [#############################################] Time:  0:00:00  27.3 KiB/s
100% [#############################################] Time:  0:00:00  20.0 KiB/s
100% [#############################################] Time:  0:00:00   1.4 KiB/s
100% [#############################################] Time:  0:00:00  23.7 KiB/s
100% [#############################################] Time:  0:00:00  37.1 KiB/s
100% [#############################################] Time:  0:00:00  14.1 KiB/s
100% [#############################################] Time:  0:00:00  17.0 KiB/s
100% [#############################################] Time:  0:00:00  27.0 KiB/s
100% [#############################################] Time:  0:00:00  17.0 KiB/s
100% [#############################################] Time:  0:00:00  23.7 KiB/s
100% [#############################################] Time:  0:00:00  33.0 KiB/s
100% [#############################################] Time:  0:00:00  49.0 KiB/s
100% [#############################################] Time:  0:00:00  20.4 KiB/s
100% [#############################################] Time:  0:00:00  18.0 KiB/s
100% [#############################################] Time:  0:00:00  23.7 KiB/s
100% [#############################################] Time:  0:00:00  22.3 KiB/s
100% [#############################################] Time:  0:00:00  14.4 KiB/s
100% [#############################################] Time:  0:00:00  32.5 KiB/s
100% [#############################################] Time:  0:00:00   1.5 KiB/s
100% [#############################################] Time:  0:00:00  19.8 KiB/s
100% [#############################################] Time:  0:00:00  33.2 KiB/s
100% [#############################################] Time:  0:00:00  17.1 KiB/s
100% [#############################################] Time:  0:00:00  16.7 KiB/s
100% [#############################################] Time:  0:00:02  10.1 KiB/s
100% [#############################################] Time:  0:00:00   3.0 KiB/s
100% [#############################################] Time:  0:00:00  52.3 KiB/s
100% [#############################################] Time:  0:00:00  24.7 KiB/s
100% [#############################################] Time:  0:00:00   3.2 KiB/s
100% [#############################################] Time:  0:00:00  31.8 KiB/s
100% [#############################################] Time:  0:00:00  18.4 KiB/s
100% [#############################################] Time:  0:00:00  32.3 KiB/s
100% [#############################################] Time:  0:00:00  17.1 KiB/s
100% [#############################################] Time:  0:00:00  43.9 KiB/s
100% [#############################################] Time:  0:00:00  46.2 KiB/s
100% [#############################################] Time:  0:00:00  31.8 KiB/s
100% [#############################################] Time:  0:00:01  15.1 KiB/s
100% [#############################################] Time:  0:00:01  13.7 KiB/s
100% [#############################################] Time:  0:00:00  23.2 KiB/s
100% [#############################################] Time:  0:00:00  28.9 KiB/s
100% [#############################################] Time:  0:00:00  23.4 KiB/s
100% [#############################################] Time:  0:00:00  52.7 KiB/s
100% [#############################################] Time:  0:00:00  30.4 KiB/s
100% [#############################################] Time:  0:00:00  52.5 KiB/s
100% [#############################################] Time:  0:00:00  26.1 KiB/s
100% [#############################################] Time:  0:00:00  36.6 KiB/s
100% [#############################################] Time:  0:00:00  32.6 KiB/s
100% [#############################################] Time:  0:00:00  48.5 KiB/s
100% [#############################################] Time:  0:00:00  29.1 KiB/s
100% [#############################################] Time:  0:00:00  23.0 KiB/s
100% [#############################################] Time:  0:00:00  14.2 KiB/s
100% [#############################################] Time:  0:00:00  48.7 KiB/s
100% [#############################################] Time:  0:00:00  26.8 KiB/s
100% [#############################################] Time:  0:00:00  44.3 KiB/s
100% [#############################################] Time:  0:00:00  25.9 KiB/s
100% [#############################################] Time:  0:00:00  41.3 KiB/s
100% [#############################################] Time:  0:00:00  10.8 KiB/s
100% [#############################################] Time:  0:00:00  30.0 KiB/s
100% [#############################################] Time:  0:00:00  10.8 KiB/s
100% [#############################################] Time:  0:00:00  13.1 KiB/s
100% [#############################################] Time:  0:00:00  38.9 KiB/s
100% [#############################################] Time:  0:00:00  40.0 KiB/s
100% [#############################################] Time:  0:00:01  12.3 KiB/s
100% [#############################################] Time:  0:00:00  35.6 KiB/s
100% [#############################################] Time:  0:00:00  40.6 KiB/s
100% [#############################################] Time:  0:00:00  21.0 KiB/s
100% [#############################################] Time:  0:00:00  45.0 KiB/s
100% [#############################################] Time:  0:00:00  25.3 KiB/s
100% [#############################################] Time:  0:00:00  48.3 KiB/s
100% [#############################################] Time:  0:00:00  36.6 KiB/s
100% [#############################################] Time:  0:00:00  46.8 KiB/s
100% [#############################################] Time:  0:00:00  29.6 KiB/s
100% [#############################################] Time:  0:00:00  25.6 KiB/s
100% [#############################################] Time:  0:00:00  22.6 KiB/s
100% [#############################################] Time:  0:00:00  39.4 KiB/s
100% [#############################################] Time:  0:00:00  47.8 KiB/s
100% [#############################################] Time:  0:00:00  17.8 KiB/s
100% [#############################################] Time:  0:00:00  29.3 KiB/s
100% [#############################################] Time:  0:00:00  10.9 KiB/s
100% [#############################################] Time:  0:00:00  14.4 KiB/s
100% [#############################################] Time:  0:00:00   6.6 KiB/s
100% [#############################################] Time:  0:00:00  38.3 KiB/s
100% [#############################################] Time:  0:00:00  23.1 KiB/s
100% [#############################################] Time:  0:00:00  26.7 KiB/s
100% [#############################################] Time:  0:00:00  33.8 KiB/s
100% [#############################################] Time:  0:00:00  25.3 KiB/s
100% [#############################################] Time:  0:00:00   6.2 KiB/s
100% [#############################################] Time:  0:00:00  36.6 KiB/s
100% [#############################################] Time:  0:00:00  35.5 KiB/s
100% [#############################################] Time:  0:00:00   9.8 KiB/s
100% [#############################################] Time:  0:00:00  56.1 KiB/s
100% [#############################################] Time:  0:00:00  34.6 KiB/s
100% [#############################################] Time:  0:00:00  24.2 KiB/s
100% [#############################################] Time:  0:00:00  24.9 KiB/s
100% [#############################################] Time:  0:00:00  11.6 KiB/s
100% [#############################################] Time:  0:00:00  21.2 KiB/s
100% [#############################################] Time:  0:00:00  17.2 KiB/s
100% [#############################################] Time:  0:00:01   9.7 KiB/s
100% [#############################################] Time:  0:00:00  23.4 KiB/s
100% [#############################################] Time:  0:00:00  23.9 KiB/s
100% [#############################################] Time:  0:00:00  15.8 KiB/s
100% [#############################################] Time:  0:00:01  13.0 KiB/s
100% [#############################################] Time:  0:00:01  17.8 KiB/s
100% [#############################################] Time:  0:00:00  15.7 KiB/s
100% [#############################################] Time:  0:00:00  30.1 KiB/s
100% [#############################################] Time:  0:00:00  19.2 KiB/s
100% [#############################################] Time:  0:00:00  14.5 KiB/s
100% [#############################################] Time:  0:00:00  33.1 KiB/s
100% [#############################################] Time:  0:00:00  41.7 KiB/s
100% [#############################################] Time:  0:00:00  23.6 KiB/s
100% [#############################################] Time:  0:00:00  33.9 KiB/s
100% [#############################################] Time:  0:00:00  17.6 KiB/s
100% [#############################################] Time:  0:00:00  20.5 KiB/s
100% [#############################################] Time:  0:00:00  62.6 KiB/s
100% [#############################################] Time:  0:00:00  46.1 KiB/s
100% [#############################################] Time:  0:00:00  35.1 KiB/s
100% [#############################################] Time:  0:00:00  27.7 KiB/s
100% [#############################################] Time:  0:00:00  25.1 KiB/s
100% [#############################################] Time:  0:00:00  22.5 KiB/s
100% [#############################################] Time:  0:00:00  26.1 KiB/s
100% [#############################################] Time:  0:00:00  39.8 KiB/s
100% [#############################################] Time:  0:00:00  27.4 KiB/s
100% [#############################################] Time:  0:00:00   2.4 KiB/s
100% [#############################################] Time:  0:00:00  29.3 KiB/s
100% [#############################################] Time:  0:00:00  25.1 KiB/s
100% [#############################################] Time:  0:00:00  25.8 KiB/s
100% [#############################################] Time:  0:00:00  27.6 KiB/s
100% [#############################################] Time:  0:00:00  20.8 KiB/s
100% [#############################################] Time:  0:00:00  21.2 KiB/s
100% [#############################################] Time:  0:00:00  18.6 KiB/s
100% [#############################################] Time:  0:00:00  15.5 KiB/s
100% [#############################################] Time:  0:00:00  20.5 KiB/s
100% [#############################################] Time:  0:00:00  24.3 KiB/s
100% [#############################################] Time:  0:00:00  17.1 KiB/s
100% [#############################################] Time:  0:00:00  32.4 KiB/s
100% [#############################################] Time:  0:00:00  43.7 KiB/s
100% [#############################################] Time:  0:00:00  13.2 KiB/s
100% [#############################################] Time:  0:00:00  17.3 KiB/s
100% [#############################################] Time:  0:00:00  18.9 KiB/s
100% [#############################################] Time:  0:00:00  35.2 KiB/s
100% [#############################################] Time:  0:00:00  37.0 KiB/s
100% [#############################################] Time:  0:00:00  21.7 KiB/s
100% [#############################################] Time:  0:00:00  29.9 KiB/s
100% [###############################################] Time:  0:00:01 797.2 B/s
100% [#############################################] Time:  0:00:01  19.4 KiB/s
100% [#############################################] Time:  0:00:00   6.3 KiB/s
100% [#############################################] Time:  0:00:00  32.2 KiB/s
100% [#############################################] Time:  0:00:00  13.8 KiB/s
100% [#############################################] Time:  0:00:00  38.0 KiB/s
100% [#############################################] Time:  0:00:00  36.1 KiB/s
100% [#############################################] Time:  0:00:00  30.1 KiB/s
100% [#############################################] Time:  0:00:00  14.3 KiB/s
100% [#############################################] Time:  0:00:00  37.3 KiB/s
100% [#############################################] Time:  0:00:00  10.9 KiB/s
100% [#############################################] Time:  0:00:00  42.2 KiB/s
100% [#############################################] Time:  0:00:00  18.6 KiB/s
100% [#############################################] Time:  0:00:00  39.7 KiB/s
100% [#############################################] Time:  0:00:00  35.3 KiB/s
100% [#############################################] Time:  0:00:00  21.5 KiB/s
100% [#############################################] Time:  0:00:00  25.6 KiB/s
100% [#############################################] Time:  0:00:00  19.9 KiB/s
100% [#############################################] Time:  0:00:00  14.9 KiB/s
100% [#############################################] Time:  0:00:00  14.4 KiB/s
100% [#############################################] Time:  0:00:00  22.1 KiB/s
100% [#############################################] Time:  0:00:00  29.0 KiB/s
100% [#############################################] Time:  0:00:00  25.2 KiB/s
100% [#############################################] Time:  0:00:01  24.9 KiB/s
100% [#############################################] Time:  0:00:01  17.4 KiB/s
100% [#############################################] Time:  0:00:00  19.5 KiB/s
100% [#############################################] Time:  0:00:00  17.9 KiB/s
100% [#############################################] Time:  0:00:00  17.6 KiB/s
100% [#############################################] Time:  0:00:00  41.8 KiB/s
100% [#############################################] Time:  0:00:00  16.7 KiB/s
100% [#############################################] Time:  0:00:00  20.4 KiB/s
100% [#############################################] Time:  0:00:00  47.1 KiB/s
100% [#############################################] Time:  0:00:00  15.5 KiB/s
100% [#############################################] Time:  0:00:00  25.4 KiB/s
100% [#############################################] Time:  0:00:00  34.2 KiB/s
100% [#############################################] Time:  0:00:00  25.6 KiB/s
100% [#############################################] Time:  0:00:00  36.4 KiB/s
100% [#############################################] Time:  0:00:00  21.6 KiB/s
100% [#############################################] Time:  0:00:00  48.8 KiB/s
100% [#############################################] Time:  0:00:00  19.1 KiB/s
100% [#############################################] Time:  0:00:00  45.3 KiB/s
100% [#############################################] Time:  0:00:00  40.6 KiB/s
100% [#############################################] Time:  0:00:00  32.9 KiB/s
100% [#############################################] Time:  0:00:00  56.0 KiB/s
100% [#############################################] Time:  0:00:00  61.9 KiB/s

In [ ]:
!ls gdc_download | head

ls: cannot access 'gdc_download': No such file or directory

In [ ]:
!find . -name "*.maf.gz" | head

./4f4c30a2-cc49-4993-b861-8a1c3c38020f/fe3892db-076d-4223-b60e-5613e10bdd7e.wxs.aliquot_ensemble_masked.maf.gz
./a9e4beea-4851-43dd-bbba-58139b6bc034/6ab5e5e3-0bb8-4ad0-b050-82794af054aa.wxs.aliquot_ensemble_masked.maf.gz
./5442f31d-8273-4f6c-aa47-72b5b0cbb198/2e973347-8997-4031-9686-a4a3601f96f6.wxs.aliquot_ensemble_masked.maf.gz
./10bd25f7-6193-4b79-9902-70681aca386b/0e3a16bd-a03e-44e6-bb97-f3c335a71585.wxs.aliquot_ensemble_masked.maf.gz
./b35fa503-b72f-4ef3-9214-fbea996981b2/ee74cb2a-f835-493d-b178-e6e4d9e67ee3.wxs.aliquot_ensemble_masked.maf.gz
./00a6589b-6c02-4b41-b363-fb5e7151675b/ab07fdf2-e02f-4e37-a0d6-0c42813c3a92.wxs.aliquot_ensemble_masked.maf.gz
./dc8ee3a4-493b-482b-84a1-7ca4d592a4c7/5164e8bf-589f-40fa-a34e-bc4b80af9ee8.wxs.aliquot_ensemble_masked.maf.gz
./683546ab-f956-42cb-8220-2d57deac5353/af74add9-038e-4e6c-aa51-9a6162e99d5c.wxs.aliquot_ensemble_masked.maf.gz
./f23269cc-1ce9-474f-8b05-6365f76fcef0/4e863178-ebf2-492b-a025-afc97cc1515b.wxs.aliquot_ensemble_masked.maf.gz
./d7b171dc-eafe-43da-8df6-a909cfd362b2/2d0b5003-ffff-4c0f-9065-911d581195c4.wxs.aliquot_ensemble_masked.maf.gz

In [ ]:
!find . -name "*.maf.gz" | wc -l

994

In [ ]:
import pandas as pd
import gzip
import os

maf_list = []

for root, dirs, files in os.walk("."):
    for file in files:
        if file.endswith(".maf.gz"):
            path = os.path.join(root, file)

            try:
                with gzip.open(path, "rt") as f:
                    df = pd.read_csv(f, sep="\t", comment="#", low_memory=False)
                    maf_list.append(df)
            except Exception as e:
                print("Skipped:", path)

print("Files loaded:", len(maf_list))

mutation_df = pd.concat(maf_list, ignore_index=True)

print("Mutation dataframe shape:", mutation_df.shape)

Files loaded: 994

/tmp/ipykernel_540/1069020658.py:21: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  mutation_df = pd.concat(maf_list, ignore_index=True)

Mutation dataframe shape: (87957, 140)

In [ ]:
mutation_df = mutation_df[[
    "Tumor_Sample_Barcode",
    "Hugo_Symbol",
    "Variant_Classification"
]]

mutation_df.head()

           Tumor_Sample_Barcode Hugo_Symbol Variant_Classification
0  TCGA-32-2616-01A-01D-1495-08      SAMD11      Missense_Mutation
1  TCGA-32-2616-01A-01D-1495-08        AGRN      Missense_Mutation
2  TCGA-32-2616-01A-01D-1495-08        DVL1                 Silent
3  TCGA-32-2616-01A-01D-1495-08         SKI      Missense_Mutation
4  TCGA-32-2616-01A-01D-1495-08        TP73      Missense_Mutation

In [ ]:
mutation_df["Patient_ID"] = mutation_df["Tumor_Sample_Barcode"].str[:12]

mutation_df.head()

,Tumor_Sample_Barcode,Hugo_Symbol,Variant_Classification,Patient_ID
0,TCGA-32-2616-01A-01D-1495-08,SAMD11,Missense_Mutation,TCGA-32-2616
1,TCGA-32-2616-01A-01D-1495-08,AGRN,Missense_Mutation,TCGA-32-2616
2,TCGA-32-2616-01A-01D-1495-08,DVL1,Silent,TCGA-32-2616
3,TCGA-32-2616-01A-01D-1495-08,SKI,Missense_Mutation,TCGA-32-2616
4,TCGA-32-2616-01A-01D-1495-08,TP73,Missense_Mutation,TCGA-32-2616

In [ ]:
top_genes = mutation_df["Hugo_Symbol"].value_counts().head(50)

print(top_genes)

Hugo_Symbol
TP53      491
IDH1      433
TTN       412
ATRX      272
MUC16     195
PTEN      182
EGFR      171
CIC       144
NF1       113
OBSCN     100
FLG        96
PIK3CA     95
RYR2       88
LRP2       86
MUC17      77
DST        77
HMCN1      77
SYNE1      72
PIK3R1     70
PCLO       67
PKHD1      67
DNAH5      64
USH2A      64
SPTA1      62
DNAH3      59
DNAH11     56
AHNAK      55
RELN       55
ADGRV1     55
DNAH2      55
LRP1       54
FAT2       53
AHNAK2     52
NOTCH1     52
FUBP1      51
DNAH8      48
COL6A3     48
APOB       48
LRP1B      48
RB1        48
HYDIN      46
NEB        45
FCGBP      45
MACF1      45
DSP        44
RYR3       44
RYR1       42
MXRA5      42
FRAS1      42
CSMD3      42
Name: count, dtype: int64

In [ ]:
selected_genes = [
    "IDH1",
    "TP53",
    "ATRX",
    "EGFR",
    "PTEN",
    "NF1"
]

mutation_df = mutation_df[
    mutation_df["Hugo_Symbol"].isin(selected_genes)
]

In [ ]:
mutation_matrix = pd.crosstab(
    mutation_df["Patient_ID"],
    mutation_df["Hugo_Symbol"]
)

mutation_matrix = (mutation_matrix > 0).astype(int)

mutation_matrix.reset_index(inplace=True)

mutation_matrix.head()

Hugo_Symbol    Patient_ID  ATRX  EGFR  IDH1  NF1  PTEN  TP53
0            TCGA-02-0003     0     1     0    0     0     1
1            TCGA-02-0033     0     0     0    0     0     1
2            TCGA-02-0055     0     0     0    0     1     1
3            TCGA-02-2466     0     1     0    0     0     0
4            TCGA-02-2470     0     0     0    0     1     0

In [ ]:
print(mutation_matrix.shape)

(714, 7)

In [ ]:
import numpy as np

gbm = pd.read_csv("/content/drive/MyDrive/clinical.project-tcga-gbm.2026-03-03/clinical.tsv", sep="\t")

# Replace missing indicators
gbm = gbm.replace("'--", np.nan)
gbm = gbm.replace("--", np.nan)

gbm_clean = gbm[[
    "cases.submitter_id",
    "demographic.vital_status",
    "demographic.days_to_death",
    "diagnoses.days_to_last_follow_up",
    "demographic.age_at_index",
    "demographic.gender",
    "demographic.race"
]].copy()

gbm_clean.columns = [
    "Patient_ID",
    "vital_status",
    "days_to_death",
    "days_to_last_follow_up",
    "age",
    "gender",
    "race"
]

# Convert numeric
gbm_clean["days_to_death"] = pd.to_numeric(gbm_clean["days_to_death"], errors="coerce")
gbm_clean["days_to_last_follow_up"] = pd.to_numeric(gbm_clean["days_to_last_follow_up"], errors="coerce")
gbm_clean["age"] = pd.to_numeric(gbm_clean["age"], errors="coerce")

# Survival time
gbm_clean["Overall_Survival_Days"] = gbm_clean["days_to_death"]
gbm_clean["Overall_Survival_Days"] = gbm_clean["Overall_Survival_Days"].fillna(
    gbm_clean["days_to_last_follow_up"]
)

# Event
gbm_clean["Event"] = gbm_clean["vital_status"].apply(
    lambda x: 1 if x == "Dead" else 0
)

# Keep required columns
gbm_clean = gbm_clean[[
    "Patient_ID",
    "Overall_Survival_Days",
    "Event",
    "age",
    "gender",
    "race"
]]

# Remove rows without survival
gbm_clean = gbm_clean.dropna(subset=["Overall_Survival_Days"])

# Drop duplicates (CRITICAL)
gbm_clean = gbm_clean.drop_duplicates(subset=["Patient_ID"])

print("GBM patients:", len(gbm_clean))
print(gbm_clean["race"].value_counts(dropna=False))

GBM patients: 596
race
white                        507
black or african american     51
not reported                  25
asian                         13
Name: count, dtype: int64

/tmp/ipykernel_540/2432029691.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  gbm = gbm.replace("'--", np.nan)

In [ ]:
import numpy as np

lgg = pd.read_csv("/content/drive/MyDrive/clinical.project-tcga-lgg.2026-03-03/clinical.tsv", sep="\t")

# Replace missing indicators
lgg = lgg.replace("'--", np.nan)
lgg = lgg.replace("--", np.nan)

lgg_clean = lgg[[
    "cases.submitter_id",
    "demographic.vital_status",
    "demographic.days_to_death",
    "diagnoses.days_to_last_follow_up",
    "demographic.age_at_index",
    "demographic.gender",
    "demographic.race"
]].copy()

lgg_clean.columns = [
    "Patient_ID",
    "vital_status",
    "days_to_death",
    "days_to_last_follow_up",
    "age",
    "gender",
    "race"
]

# Convert numeric
lgg_clean["days_to_death"] = pd.to_numeric(lgg_clean["days_to_death"], errors="coerce")
lgg_clean["days_to_last_follow_up"] = pd.to_numeric(lgg_clean["days_to_last_follow_up"], errors="coerce")
lgg_clean["age"] = pd.to_numeric(lgg_clean["age"], errors="coerce")

# Survival time
lgg_clean["Overall_Survival_Days"] = lgg_clean["days_to_death"]
lgg_clean["Overall_Survival_Days"] = lgg_clean["Overall_Survival_Days"].fillna(
    lgg_clean["days_to_last_follow_up"]
)

# Event
lgg_clean["Event"] = lgg_clean["vital_status"].apply(
    lambda x: 1 if x == "Dead" else 0
)

# Keep required columns
lgg_clean = lgg_clean[[
    "Patient_ID",
    "Overall_Survival_Days",
    "Event",
    "age",
    "gender",
    "race"
]]

# Remove rows without survival
lgg_clean = lgg_clean.dropna(subset=["Overall_Survival_Days"])

# Drop duplicates (CRITICAL)
lgg_clean = lgg_clean.drop_duplicates(subset=["Patient_ID"])

print("LGG patients:", len(lgg_clean))
print(lgg_clean["race"].value_counts(dropna=False))

LGG patients: 515
race
white                               475
black or african american            21
asian                                 8
not reported                          5
Unknown                               5
american indian or alaska native      1
Name: count, dtype: int64

/tmp/ipykernel_540/62127440.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  lgg = lgg.replace("'--", np.nan)

In [ ]:
gbm_clean["Tumor_Type"] = 1   # GBM
lgg_clean["Tumor_Type"] = 0   # LGG

In [ ]:
clinical_merged = pd.concat([gbm_clean, lgg_clean], axis=0)

print("Total Patients:", len(clinical_merged))
print("Race distribution:\n", clinical_merged["race"].value_counts(dropna=False))

Total Patients: 1111
Race distribution:
 race
white                               982
black or african american            72
not reported                         30
asian                                21
Unknown                               5
american indian or alaska native      1
Name: count, dtype: int64

In [ ]:
clinical_merged["race"] = clinical_merged["race"].replace(
    ["not reported", "Unknown"],
    np.nan
)

# Merge small categories
clinical_merged["race"] = clinical_merged["race"].replace(
    ["american indian or alaska native"],
    "other"
)

# Fill missing
clinical_merged["race"] = clinical_merged["race"].fillna("other")

In [ ]:
clinical_merged["gender"] = clinical_merged["gender"].map({
    "male": 1,
    "female": 0
})

In [ ]:
clinical_merged = pd.get_dummies(
    clinical_merged,
    columns=["race"],
    drop_first=True
)

In [ ]:
print(clinical_merged.shape)
print(clinical_merged.head())

(1111, 9)
      Patient_ID  Overall_Survival_Days  Event   age  gender  Tumor_Type  \
0   TCGA-14-1034                  485.0      1  60.0       0           1
9   TCGA-06-0133                  435.0      1  64.0       1           1
16  TCGA-06-0140                    6.0      1  86.0       1           1
18  TCGA-06-0171                  399.0      1  65.0       1           1
26  TCGA-06-0402                    8.0      1  71.0       1           1

    race_black or african american  race_other  race_white
0                            False        True       False
9                            False       False        True
16                           False       False        True
18                           False       False        True
26                           False       False        True

In [ ]:
race_cols = [
    "race_black or african american",
    "race_other",
    "race_white"
]

clinical_merged[race_cols] = clinical_merged[race_cols].astype(int)

In [ ]:
clinical_merged.dtypes

Patient_ID                         object
Overall_Survival_Days             float64
Event                               int64
age                               float64
gender                              int64
Tumor_Type                          int64
race_black or african american      int64
race_other                          int64
race_white                          int64
dtype: object

In [ ]:
final_dataset = clinical_merged.merge(
    mutation_matrix,
    on="Patient_ID",
    how="left"
)

final_dataset = final_dataset.fillna(0)

print(final_dataset.shape)

(1111, 15)

In [ ]:
final_dataset.columns

Index(['Patient_ID', 'Overall_Survival_Days', 'Event', 'age', 'gender',
       'Tumor_Type', 'race_black or african american', 'race_other',
       'race_white', 'ATRX', 'EGFR', 'IDH1', 'NF1', 'PTEN', 'TP53'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

clinical_cols = ["age"]

final_dataset[clinical_cols] = scaler.fit_transform(
    final_dataset[clinical_cols]
)

In [ ]:
final_dataset.to_csv("trimodal_clinical_genomic_dataset.csv", index=False)